from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from geopy.geocoders import Nominatim


def extract_geo_candidates(text: str) -> dict[str, Any]:
	gps_matches: list[dict[str, Any]] = []

	# Decimal lat,lon pattern, ex: 37.5665,126.9780
	decimal_pattern = re.compile(r"(-?\d{1,2}\.\d+)[,\s]+(-?\d{1,3}\.\d+)")
	for m in decimal_pattern.finditer(text):
		lat = float(m.group(1))
		lon = float(m.group(2))
		if -90 <= lat <= 90 and -180 <= lon <= 180:
			gps_matches.append({"raw": m.group(0), "lat": lat, "lon": lon, "source": "regex_decimal"})

	return {"gps_matches": gps_matches}


def geocode_text_candidates(detections: list[dict[str, Any]], top_k: int = 5) -> list[dict[str, Any]]:
	geolocator = Nominatim(user_agent="ocr_geo_extractor")
	sorted_dets = sorted(
		detections,
		key=lambda x: float(x.get("confidence", 0.0)),
		reverse=True,
	)[:top_k]
	out: list[dict[str, Any]] = []

	for det in sorted_dets:
		text_raw = str(det.get("text", "")).strip()
		matched_place = str(det.get("matched_place", "")).strip()
		query_text = matched_place if matched_place else text_raw
		if len(query_text) < 2:
			continue

		try:
			location = geolocator.geocode(query_text, addressdetails=True)
		except Exception as exc:
			out.append(
				{
					"idx": int(det.get("idx", -1)),
					"text": query_text,
					"geocoded": False,
					"reason": str(exc),
				}
			)
			continue

		if location is None:
			out.append(
				{
					"idx": int(det.get("idx", -1)),
					"text": query_text,
					"geocoded": False,
					"reason": "not found",
				}
			)
			continue

		out.append(
			{
				"idx": int(det.get("idx", -1)),
				"text": text_raw,
				"matched_place": matched_place,
				"geocoded": True,
				"lat": float(location.latitude),
				"lon": float(location.longitude),
				"display_name": location.address,
			}
		)

	return out


def run_geo_coding(ocr_json_path: Path, output_dir: Path | None, top_k: int) -> Path:
	data = json.loads(ocr_json_path.read_text(encoding="utf-8"))
	detections = data.get("detections", [])
	if not isinstance(detections, list):
		raise ValueError(f"invalid detections format in: {ocr_json_path}")

	full_text = " ".join(str(d.get("text", "")) for d in detections)
	gps_candidates = extract_geo_candidates(full_text)
	geocode_results = geocode_text_candidates(detections, top_k=max(1, top_k))

	image_path = str(data.get("image", ""))
	out_dir = output_dir if output_dir is not None else ocr_json_path.parent
	out_dir.mkdir(parents=True, exist_ok=True)

	stem = ocr_json_path.name
	if stem.endswith("_ocr_detections.json"):
		stem = stem[: -len("_ocr_detections.json")]
	else:
		stem = ocr_json_path.stem

	out_path = out_dir / f"{stem}_geocode_candidates.json"
	out_payload = {
		"image": image_path,
		"mode": data.get("mode", "kr_place_whitelist_only"),
		"source_detection_json": str(ocr_json_path),
		"geocode_candidates": geocode_results,
		"gps_regex_candidates": gps_candidates,
	}
	out_path.write_text(json.dumps(out_payload, ensure_ascii=False, indent=2), encoding="utf-8")
	return out_path


def build_arg_parser() -> argparse.ArgumentParser:
	parser = argparse.ArgumentParser(
		description="Run geocoding from OCR detection JSON generated by ocr.py"
	)
	parser.add_argument(
		"--ocr-json",
		required=True,
		help="Path to *_ocr_detections.json",
	)
	parser.add_argument(
		"--output-dir",
		default="./path-to-gpx/output/geocoding/",
		help="Output directory for geocode JSON",
	)
	parser.add_argument(
		"--top-k",
		type=int,
		default=5,
		help="Try geocoding for top-k high-confidence texts",
	)
	return parser


def main() -> int:
	parser = build_arg_parser()
	args = parser.parse_args()

	ocr_json_path = Path(args.ocr_json)
	if not ocr_json_path.exists() or not ocr_json_path.is_file():
		raise FileNotFoundError(f"ocr detection json not found: {ocr_json_path}")

	out_dir = Path(args.output_dir) if args.output_dir else None
	out_path = run_geo_coding(ocr_json_path=ocr_json_path, output_dir=out_dir, top_k=args.top_k)
	print(f"[DONE] geocode json: {out_path}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
